### ISSUE TITLE
Error running retrieveBRENDA.py

### ISSUE THREAD

**Issue by tutentaten** [SysBioChalmers/GECKO#78]
Running rertrieBRENDA.py I receive the following output:

Traceback (most recent call last):
  File "C:/Users/cga32/Desktop/GECKO_software/geckomat/brenda_parser/retrieveBRENDA.py", line 134, in <module>
    extract_field(field,last_EC)
  File "C:/Users/cga32/Desktop/GECKO_software/geckomat/brenda_parser/retrieveBRENDA.py", line 32, in extract_field
    ECstring = client.getEcNumbersFromKmValue(credentials)
  File "C:\Python27\lib\site-packages\SOAPpy\Client.py", line 547, in __call__
    return self.__r_call(*args, **kw)
  File "C:\Python27\lib\site-packages\SOAPpy\Client.py", line 569, in __r_call
    self.__hd, self.__ma)
  File "C:\Python27\lib\site-packages\SOAPpy\Client.py", line 432, in __call
    timeout = self.timeout)
  File "C:\Python27\lib\site-packages\SOAPpy\Client.py", line 331, in call
    raise HTTPError(code, msg)
SOAPpy.Errors.HTTPError: <HTTPError 302 Found>

It is my understanding that this error may appear when redirected to a login page. I have verified that the email and password I have written into the retriveBRENDA.py script is working.  Do you have any ideas what might be wrong?

*Solved this error by changing some indents in the aforemention python script.

**Comment by IVANDOMENZAIN** [comment]
Thanks for letting us know @tutentaten We'll fix this in a `fix` branch.

**Comment by BenjaSanchez** [comment]
@sulheim might have found a solution for this:
> the url has changed: It is now `https://www.brenda-enzymes.org/soap/brenda_server.php` not `http://`
